Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
svs = np.array([[1, 0], [np.log2(50), 0], [np.log2(50), 10**6], [1, 10**6], [1, 0]]).T
tns = np.array([[np.log2(25), 0], [np.log2(65536), 0], [np.log2(65536), 100], [np.log2(25), 100], [np.log2(25), 0]]).T

import matplotlib.pyplot as plt
plt.figure(figsize=(15,8))
plt.xlim(2, 16)
plt.ylim(1, 10**6)
plt.yscale('log')
plt.fill(svs[0], svs[1], fc='green', alpha=0.5)
plt.fill(tns[0], tns[1], fc='blue', alpha=0.5)
loc = [i for i in range(1, 17)]
lab = [2**i for i in range(1, 17)]
plt.xticks(loc, lab, fontsize=15)
plt.yticks(fontsize=15)
plt.text(7, 8, "Tensor-Network Simulators", fontsize=24)
plt.text(3, 8, "State-Vector Simulators", fontsize=24, rotation=90)
plt.show()
------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 1[39m
[32m----> [39m[32m1[39m svs = [43mnp[49m.array([[[32m1[39m, [32m0[39m], [np.log2([32m50[39m), [32m0[39m], [np.log2([32m50[39m), [32m10[39m**[32m6[39m], [[32m1[39m, [32m10[39m**[32m6[39m], [[32m1[39m, [32m0[39m]]).T
[32m      2[39m tns = np.array([[np.log2([32m25[39m), [32m0[39m], [np.log2([32m65536[39m), [32m0[39m], [np.log2([32m65536[39m), [32m100[39m], [np.log2([32m25[39m), [32m100[39m], [np.log2([32m25[39m), [32m0[39m]]).T
[32m      4[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mmatplotlib[39;00m[34;01m.[39;00m[34;01mpyplot[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mplt[39;00m

[31mNameError[39m: name 'np' is not defined

